# Generated by Django 6.0.3 on 2026-03-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('BDT', 'BDT ৳'), ('USD', 'USD $'), ('EURO', 'EURO €'), ('INR', 'INR ₹')], default='BDT', max_length=10),
        ),
    ]
