# Generated by Django 6.0.3 on 2026-03-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
