# Generated by Django 6.0.3 on 2026-03-13 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_company_overview_customuser_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_overview',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.AddField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
