# Generated by Django 6.0.3 on 2026-03-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_company_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_overview',
            field=models.TextField(blank=True, default='Tech Solutions Ltd. is a fast-growing software company specializing in enterprise systems, mobile apps, and cloud services.', null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='job_title',
            field=models.CharField(blank=True, default='Senior HR Manager', max_length=150, null=True),
        ),
    ]
