# Generated by Django 6.0.3 on 2026-03-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_recruiterprofile_company_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com/in/officialontar', null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, default='+880 1234-567890', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='summary',
            field=models.TextField(blank=True, default='Passionate frontend developer with strong knowledge of HTML, CSS, Tailwind, JavaScript, and React. Looking for opportunities to build modern web apps.', null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='title',
            field=models.CharField(blank=True, default='Frontend Developer', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.TextField(blank=True, default='Junior Web Developer — ABC Tech\n2024 - Present\nWorked on responsive UI, landing pages, and dashboard interfaces.', null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True, default='HTML CSS Tailwind JavaScript React', null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=150, null=True),
        ),
    ]
